### ISSUE TITLE
Issue1

### ISSUE THREAD

**Issue by erorpetar** [erorpetar/DOConGitHubBootcamp#1]
@branislavrajkov

# BUG

- [ ] Task1
- [ ] #2

🐛 

```
- name: "Run helmfile for release {{ release }}"
      shell: source {{ envir }}/.env && helmfile -e {{ envir }} -l name={{ release }} destroy
      args:
        executable: /bin/bash  
      register: output
      when: release != "all"
```
